In [3]:

import numpy as np
import cv2

img = cv2.imread('/home/amitash/Documents/UCSD /ECE-276A/ECE276A_PR1/bin_detection/data/trial/0001.jpg', 1)


print(img)

[[[223 215 208]
  [213 205 198]
  [207 200 191]
  ...
  [193 185 186]
  [183 175 176]
  [178 172 173]]

 [[233 223 216]
  [232 222 215]
  [235 226 217]
  ...
  [255 245 247]
  [249 241 241]
  [255 247 248]]

 [[232 220 214]
  [231 219 213]
  [231 220 212]
  ...
  [249 237 237]
  [249 237 235]
  [248 236 236]]

 ...

 [[ 26 114  74]
  [ 59 150 117]
  [ 41 138 118]
  ...
  [ 47 107  66]
  [  0  50  17]
  [  0  43  20]]

 [[ 27 116  76]
  [ 36 127  94]
  [ 73 170 150]
  ...
  [ 12  74  34]
  [ 36  91  58]
  [  1  57  34]]

 [[ 17 106  66]
  [ 19 110  77]
  [ 32 129 109]
  ...
  [  0  49   9]
  [ 28  85  52]
  [ 34  90  69]]]
